language: cpp

compiler:
  - gcc
  - clang

branches:
  except:
    - all_in_one

# Problem with clang
# http://stackoverflow.com/questions/15747223/why-does-this-basic-thread-program-fail-with-clang-but-pass-in-g

before_install:
# g++4.9
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
# clang3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
# boost 1.58
  - wget http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.bz2/download
  - tar xfj download
  - rm download

install:
  - sudo apt-get update -qq
# g++4.9
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" == "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
# clang3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
# boost 1.58
  - cd boost_1_58_0
  - ./bootstrap.sh --with-libraries=system
  - ./b2
  - sudo ./b2 install &>/dev/null
  - cd ..
  - rm -rf boost_1_58_0

before_script:
  - mkdir build
  - cd build
  - cmake -DTRANSPORT="TCP" ..

script:
  - make -j 4
  - make check
